name: InterpolAI
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
    - tensorflow<2.11
    - numpy==1.26.4
    - imageio
    - natsort
    - tqdm
    - jupyter