name: interpolai2
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
    - tensorflow<2.11
    - numpy==1.21.6
    - imageio
    - natsort
    - tqdm
    - jupyter